### ISSUE TITLE
Offline support for projects with Zenodo caching

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#134] opened 2022-08-01 02:10 UTC
You cannot build a project offline if it has Zenodo caching. The build fails, complaining that it could not connect to Zenodo. It would be nice if it just told you that the connection failed, but still ran the build. For example, I discovered I couldn't build changes to `ms.tex` on a flight!

**Comment by rodluger** [comment] 2022-08-01 12:42
Cache-related operations should fail non-fatally for this reason. There must be an exception I'm not catching properly. Can you reproduce the error and send me the terminal output and build logs (in `.showyourwork/logs`)? Thanks!

**Comment by jfcrenshaw** [comment] 2022-08-01 20:01
First I run `showyourwork` with an internet connection:
```python
❯ showyourwork
User authentication for 10.5072/zenodo.1086358 is valid.
Done!
```

Then, I turn off my wifi and run `showyourwork` again:
```python
❯ showyourwork
ConnectionError in line 69 of /Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/workflow/build.smk:
HTTPSConnectionPool(host='sandbox.zenodo.org', port=443): Max retries exceeded with url: /api/deposit/depositions?q=recid%3A1086358+conceptrecid%3A1086358&all_versions=1&access_token=FAKE_TOKEN_I_REPLACED (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1032db370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/workflow/build.smk", line 69, in <module>
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/userrules.py", line 36, in process_user_rules
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 116, in patch_snakemake_cache
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/zenodo.py", line 112, in __init__
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/showyourwork/zenodo.py", line 246, in check_if_user_is_owner
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/api.py", line 76, in get
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/api.py", line 61, in request
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
```

Here is the contents of the build log `.showyourwork/logs/showyourwork.log`:
```
Testing if user is authenticated for 10.5072/zenodo.1086358...
```

**Comment by rodluger** [comment] 2022-08-03 15:54
OK, thanks, I'll look into this. In the meantime, you can always comment out the DOIs in the `zenodo.yml` file to bypass cache checks.

**Comment by rodluger** [comment] 2022-08-09 21:31
@jfcrenshaw Can you upgrade your workflow to use

```
version: a5ec1629900acce0a67e81f41288a72a84adefc9
```

of `showyourwork` and give it a spin in offline mode to see if this is fixed?

**Comment by jfcrenshaw** [comment] 2022-08-10 17:19
I got a different error this time:

```
❯ showyourwork
Traceback (most recent call last):
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x107470640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jfcrenshaw/bibfile/main/My%20Library.bib (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107470640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/workflow.py", line 769, in execute
    dag.init()
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 179, in init
    job = self.update([job], progress=progress, create_inventory=True)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 759, in update
    self.update_(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 874, in update_
    selected_job = self.update(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 759, in update
    self.update_(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 874, in update_
    selected_job = self.update(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 759, in update
    self.update_(
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/dag.py", line 863, in update_
    if not res.file.exists:
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/io.py", line 452, in exists
    return self.exists_remote
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/io.py", line 246, in wrapper
    v = func(self, *args, **kwargs)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/io.py", line 473, in exists_remote
    return self.remote_object.exists()
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/remote/HTTP.py", line 159, in exists
    with self.httpr(verb="HEAD") as httpr:
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/snakemake/remote/HTTP.py", line 152, in httpr
    r = requests.head(url, *args_to_use, **kwargs_to_use)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jfcrenshaw/.showyourwork/env/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /jfcrenshaw/bibfile/main/My%20Library.bib (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107470640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by jfcrenshaw** [comment] 2022-08-10 17:23
Okay so that is caused by something specific to my snakefile.

I have a rule that downloads my bib file from github:
```
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
HTTP = HTTPRemoteProvider()

rule download_bib_file:
    input:
        HTTP.remote("https://raw.githubusercontent.com/jfcrenshaw/bibfile/main/My%20Library.bib")
    output:
        "src/tex/bib.bib"
    shell:
        "cp {input[0]} {output[0]}"
```
If I comment this rule out, then the new version runs offline. 

Can you tell if this is a `showyourwork` problem, or is it a `snakemake` thing? Also, no worries if you don't want to use time supporting this use case. I can always just comment that out when I don't have wifi, since the rule can never run offline anyway. (Note, this is failing in a case where that rule doesn't even need to run, because the bib file is already present. But the workflow doesn't get far enough to realize it doesn't need to run that rule.)

**Comment by dfm** [comment] 2022-08-11 13:32
This looks like a snakemake detail to me. What about if you use `keep_local=True` in `HTTP.remote`? I normally write my own snakemake rules like the following for my remote files:

```
rule download_bib_file:
    output:
        "src/tex/bib.bib"
    shell:
        "curl -L \"https://raw.githubusercontent.com/jfcrenshaw/bibfile/main/My%20Library.bib\" -o {output}"
```

which should work offline (after an initial download), I think...

**Comment by rodluger** [comment] 2022-08-11 13:51
That should work, yes. In @dfm's code the access to the remote occurs when the rule is executed. With `HTTPRemoteProvider` it occurs during dependency collection at the DAG building stage, which happens every time you run the workflow, regardless of whether files are present or not. @jfcrenshaw I'm closing this but feel free to re-open if needed.

**Closed as completed by rodluger** 2022-08-11 13:51 UTC

**Comment by rodluger** [comment] 2022-10-11 09:07
Ah, that's not a showyourwork issue. You can see in the stack trace that
the error occurs while snakemake is building the DAG and checking if the
remote file exists -- it has nothing to do with the showyourwork layer. You
could probably subclass HTTPRemoteProvider and wrap the exists method in a
try-except block, but that's something you'd have to implement on your end.
